spring:
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
    generate-ddl: true

  datasource:
    driver-class-name : org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/findmy
    username: root
    password: 123456
    initalization-mode: always
    continue-on-error: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher