spring:
  h2:
    console:
      enabled: true

    jpa:
      hibernate:
        ddl-auto: update
        properties:
          hibernate:
            format_sql: true
    generate-ddl: true

    datasource:
      # schema:
      url: jdbc:mariadb://127.0.0.1:3307/findmy
      username: root
      password: 123456
      initalization-mode: always
      continue-on-error: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher